project:
  type: default

format:
  html:
    theme: default
    toc: true
    code-fold: false
    fig-width: 8
    fig-height: 6
    embed-resources: true

execute:
  freeze: false
  engine: jupyter
  
jupyter: python3



